---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    - namespace="robertdebock/"
  matrix:
    - image="docker-alpine-openrc"
    - image="docker-alpine-openrc" tag="edge"
    # - namespace="archlinux/" image="base"
    - image="docker-centos-systemd" tag="7"
    - image="docker-centos-systemd"
    - image="docker-debian-systemd" tag="stable"
    - image="docker-debian-systemd" tag="unstable"
    - image="docker-debian-systemd"
    - image="docker-fedora-systemd"
    - image="docker-fedora-systemd" tag="rawhide"
    - namespace="opensuse/" image="leap"
    - image="docker-ubuntu-systemd" tag="rolling"
    - image="docker-ubuntu-systemd" tag="devel"
    - image="docker-ubuntu-systemd"

matrix:
  allow_failures:
    - env: image="docker-alpine-openrc" tag="edge"
    - env: image="docker-debian-systemd" tag="unstable"
    - env: image="docker-fedora-systemd" tag="rawhide"
    - env: image="docker-ubuntu-systemd" tag="rolling"
    - env: image="docker-ubuntu-systemd" tag="devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "m6xmyXNL60npAAU/MvqrBn7E64M3WA74Qmi0QV7RyLtIdjIJpHjP6VPzdw9e8o7xLtkM68uU9Ul9GVuF7Lr83aI+LQmLRJaidK+e7mwwxXEyglNhb3bJDBXw2+AO9cd923MnacrK96rsN3NhFcDHKnKWPFiFftJw+EIyyMd1AbDdzcCI0ehCIaRYKoRm9IIPx40UTCugsYiymY5fnSE2iZsaDbQK3vtMuzsVb9/bo7EAN5fMjvbEwZ3XeUK/9Q8lJJipQEwcXzWl5OvYkcLR9WojEtcCFiBsUJ/TF6SrHTJzQlS9cAnNTOXP6ydx02wjIoQP5IoIEU/yxppsBpTvgv/eIVOMdZ7iM5soFiIsFphMFtvZSyO0EdnSFmYjZNL7vzNxGOnH3iXxA+7IiuwSzBn8CQLd2uGc7/2bpMFoMYivbzFrHNYiqRp2M/nzjZIED5rmj8P95FzsYP4zam5ZvZpvMJMvzZBrfk6lR0z7qkiVdyjPitxDHd32BNVkeo0ATapYmDiqrcoJVKZ98jVluM/Mi54FbOkk7tlPtreTGZhD2lK2zI31NMp0IJQLBdkYomcmuYslgBRkVQcZQnLANwk1lyrNMzXsHNDVaUoqXQc5PYAQ36EKO5A5g5Qcn/+10R8iaFkeCsE8kqj3I1fDuBl+yDNc7maCi+t0uW+oRBc="
  email: false
