---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="alpine" tag="latest"
    - image="alpine" tag="edge"
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      - secure: "aIW1luQqTUSTWBx5Le4tXr8wlZ/yeSDQWz2Z46BjSbiRGj4o7hxXBg9AZmT2YiaC48TQxaTztztWahZ5lDuayb9f5lqU82fD3pwPeKKjachRLmpPpS+i7/l48OPq3H51nG/gOltBvLzn8y5DCmCCaHApcAHKTa9PEpoeoRtueJeqgaVKAzuTgBddS8fXYKDQPUJ0YfkzbrgGE+KXDvNDitCs8hnXPdEB475KYvLi4tfniUsauJnJwRuPINLzlYiSdtUTnAvVZTcJ4WVs6mQmXG4B4KuyIljEUb6gY5VMRlTbALqgpCVmUQjpiSNJrPqL9YmNWFcwwG7x41JuOKvwrhF/dkrrL6avGb8ytQ1ivF5/EjpJ+JJP7n6UH3o4iMcDqFy0fEbiOOwrgC0r8xeyRABol9ooVUzsJfGCcYCbuCa3z+R0u61NTBxL4OfzcZ6R5AyzuPkmQZ7uHX6k6NhqaQNAYm32ohchugNhhO55VFeXQ+7bDVdMl/mqvQa5YWQky1IDRfkkABvaOL/onRxzi59xmKgyxPqkMRM2DQAWBX9tpZPajWoh80V1jglwNRaQqYEdMC9jkiJWG+Iv0NOOcB7kcswgRAoGC9RdWDzPVSyYRfbireznkcpMnh/Tz5rR9+BbLqZC7F81S6d7XkGj4GFIwvjIDbzdLtk02psk4g8="
  email: false
