---
- name: test if haveged_write_wakeup_threshold is set correctly
  assert:
    that:
      - haveged_write_wakeup_threshold is defined
      - haveged_write_wakeup_threshold is number
      - haveged_write_wakeup_threshold | int > 0
    quiet: yes
