---
# tasks file for ansible-role-haveged
- name: install software
  package:
    name: "{{ item }}"
  with_items:
    - "{{ haveged_packages }}"

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - "{{ haveged_service }}"
  when:
    - ansible_virtualization_type != "docker"
