---
# tasks file for ansible-role-haveged
- name: install haveged
  package:
    name: haveged
    state: "{{ haveged_package_state }}"
  register: haveged_install_haveged
  until: haveged_install_haveged is succeeded
  retries: 3

- name: start and enable haveged
  service:
    name: haveged
    state: started
    enabled: true
  when:
    - ansible_virtualization_type != "docker" or haveged_ignore_docker
