---
# tasks file for ansible-role-haveged
- name: install haveged
  package:
    name: haveged
    state: "{{ haveged_package_state }}"

- name: start and enable haveged
  service:
    name: haveged
    state: started
    enabled: true
  when:
    - ansible_virtualization_type != "docker" or haveged_ignore_docker
