---
# tasks file for ansible-role-haveged
- name: install software
  package:
    name: haveged
    state: present

- name: start and enable software
  service:
    name: haveged
    state: started
    enabled: true
  when:
    - ansible_virtualization_type != "docker"
