---
# tasks file for ansible-role-haveged
- name: install software
  package:
    name: "{{ item }}"
  with_items:
    - "{{ haveged_configuration[ansible_distribution ~ '-' ~ ansible_distribution_major_version]['packages']
      | default(haveged_configuration[ansible_distribution]['packages']
      | default(haveged_configuration['default']['packages'] )) }}"

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - "{{ haveged_configuration[ansible_distribution ~ '-' ~ ansible_distribution_major_version]['services']
      | default(haveged_configuration[ansible_distribution]['services']
      | default(haveged_configuration['default']['services'] )) }}"
  when:
    - ansible_virtualization_type != "docker"
