---
# tasks file for ansible-role-haveged

- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: install haveged
  package:
    name: haveged
    state: present

- name: set write_wakeup_threshold
  sysctl:
    name: kernel.random.write_wakeup_threshold
    value: "{{ haveged_write_wakeup_threshold | string }}"
    state: present
  when:
    - ansible_connection != "docker"

- name: create /etc/systemd/system/haveged.service.d/
  file:
    path: /etc/systemd/system/haveged.service.d
    state: directory
    mode: "0755"

- name: override write_wakeup_threshold value in service
  template:
    src: custom.conf.j2
    dest: /etc/systemd/system/haveged.service.d/custom.conf
    mode: "0640"
  notify:
    - daemon reload
  when:
    - ansible_service_mgr == 'systemd'

- name: flush handlers
  meta: flush_handlers

- name: start and enable haveged
  service:
    name: haveged
    state: started
    enabled: yes
