---
# tasks file for ansible-role-haveged
- name: install haveged
  package:
    name: haveged
    state: present
  register: haveged_install_haveged
  until: haveged_install_haveged is succeeded
  retries: 3

- name: set write_wakeup_threshold
  sysctl:
    name: write_wakeup_threshold
    value: "{{ haveged_write_wakeup_threshold }}"
  when:
    - ansible_connection != "docker"

- name: create /etc/systemd/system/haveged.service.d/
  file:
    path: /etc/systemd/system/haveged.service.d
    state: directory

- name: override write_wakeup_threshold value in service
  template:
    src: custom.conf.j2
    dest: /etc/systemd/system/haveged.service.d/custom.conf
  notify:
    - daemon reload
  when:
    - ansible_service_mgr == 'systemd'

- name: flush handlers
  meta: flush_handlers

- name: start and enable haveged
  service:
    name: haveged
    state: started
    enabled: yes
