---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
    # 14.04 LTS
  - name: bootstrap-ubuntu-trusty
    image: ubuntu:trusty
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: ubuntu-trusty
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - check
    - side_effect
    - verify
    - destroy
verifier:
  name: goss
  lint:
    name: 'flake8'
